export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE';

export const NEW_ENTRY_SUCCESS = 'NEW_ENTRY_SUCCESS';
export const NEW_ENTRY_FAILURE = 'NEW_ENTRY_FAILURE';

export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS';
export const DELETE_ENTRY_FAILURE = 'DELETE_ENTRY_FAILURE';

export const UPDATE_ENTRY_SUCCESS = 'UPDATE_ENTRY_SUCCESS';
export const UPDATE_ENTRY_FAILURE = 'UPDATE_ENTRY_FAILURE';

export const VIEW_ENTRY_SUCCESS = 'VIEW_ENTRY_SUCCESS';
export const VIEW_ENTRY_FAILURE = 'VIEW_ENTRY_FAILURE';

export const SIGNOUT = 'SIGNOUT';
